config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  get "/car_dash_1", to: "pages#car_dash_1"
  get "/car_dash_2", to: "pages#car_dash_2"
  get "/car_dash_3", to: "pages#car_dash_3"
  get "/car_dash_end", to: "pages#car_dash_end"
  resources :cars, only: [:index]
  resources :car_transfers, only: [:index, :create, :show, :new, :create]
  resource :karma, only: [] do
    get :add
  end
  resources :profiles, only: [:show, :index, :update]
  resources :products, only: [:index] do
    get :buy
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/models/car_transfer.rb
class CarTransfer < ApplicationRecord
  def car_specs
    begin
      JSON.parse(car_describtion)
    rescue
      {}
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :products

  def name
    "Hans Serpei"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/car_transfers_controller.rb
class CarTransfersController < ApplicationController
  def create
    Car.create(car_transfer_params)
    redirect_to :index
  end

  def index
    @car_transfers = CarTransfer.all
  end

  def show
    @car_transfer = CarTransfer.find(car_transfer_params[:id])
    @car = Car.where(@car_transfer.car_specs)
    render layout: "car_dash"
  end

  def new
    @car_transfer = CarTransfer.new
  end

  def create
    @car_transfer = CarTransfer.create(create_car_transfer)
  end

  private

  def car_transfer_params
    params.permit(:id).to_h
  end

  def create_car_transfer
    permit_params = params.permit(:radius, :car_describtion).to_h
    {
      lat: "47.4142862",
      lng: "9.3567323",
      radius: permit_params[:radius],
      car_describtion: permit_params[:car_describtion].to_json
    }
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    objects = Car.all.find_all do |car|
      valid = false

      if filter_params.any?
        filter_params.each_with_index do |values|
          key = values.first
          value = values.last
          valid = true if car[key] == value || car[key] == value.to_i
        end
        valid
      else
        true
      end
    end
    render json: objects.to_json
  end

  private

  def filter_params
    filtered_params = params.permit(:name, :color, :seats, :horse_power).to_h
  end
end

app/controllers/karmas_controller.rb
class KarmasController < ApplicationController
  def add
    @user = current_user
    @user.karma += karma_points
    @user.save
    redirect_to profile_path(@user)
  end

  private

  def karma_params
    params.permit(:karma_id, :karma)
  end

  def karma_points
    karma_params[:karma].to_i
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def car_request
  end

  def request_taken
  end

  def car_dash_1
    render layout: 'car_dash'
  end

  def car_dash_2
    render layout: 'car_dash'
  end

  def car_dash_3
    render layout: 'car_dash'
  end

  def car_dash_end
    current_user.karma += 50
    current_user.save
    render layout: 'car_dash'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def buy
    @product = Product.find(product_id)
    if (current_user.karma - @product.price) >= 0
      current_user.products << @product
      current_user.karma -= @product.price
      current_user.save
    end

    redirect_to profile_path(current_user)
  end

  private

  def product_params
    params.permit(:product_id).to_h
  end

  def product_id
    product_params[:product_id]
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(user_id)
  end

  def index
    @users = User.order("karma DESC")
  end

  def update
    current_user.nickname = user_params[:nickname]
    current_user.save

    redirect_to profile_path current_user
  end

  private

  def user_params
    params.permit(:id, :nickname).to_h
  end

  def user_id
    user_params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/car_transfers/create.html.haml
.jumbotron
  %h1
    Your car will be there

app/views/car_transfers/index.html.haml
%table.table
  - @car_transfers.each do |car_transfer|
    %tr
      %td
        = link_to car_transfer.id, car_transfer_path(car_transfer.id)

app/views/car_transfers/new.html.haml
= form_for(@car_transfer, class: "form inline my-2 my-lg-0") do |f|
  #prepare_ride
    .form-group
      %input.form-control.mr.sm-2{ placeholder: "My Location", name: "destination"}
    .form-group
      %input.form-control.mr.sm-2{ placeholder: "Destination"}
    .form-group
      %label{ for: "exampleFormControlSelect1" }
        Area where car should be placed:
      %select.form-control#exampleFormControlSelect1{ name: "radius"}
        %option{ value: "50"} 50m
        %option{ value: "100"} 100m
        %option{ value: "200" } 200m
        %option{ value: "500" } 500m
    .form-group
      %button.btn#showMoreFiltersBtn
        Show more filters
    .form-row.align-items-center#additionalItems
      .col-auto.my-1
        %label.mr-sm-2{ for: "inlineFormCustomSelect" }
          Car Model
        %select.custom-select.mr-sm-2#inlineFormCustomSelect{ name: "car_describtion[model]"}
          %option{ selected: true }
            Choose...
          %option
            Volvo 1
          %option
            Volvo 2
          %option
            Volvo 3
          %option
            Volvo 4
          %option
            Volvo 5
          %option
            Volvo 6
      .col-auto.my-1
        %label.mr-sm-2{:for => "inlineFormCustomSelect"} Number of seats
        %select#inlineFormCustomSelect.custom-select.mr-sm-2{ name: "car_describtion[seats]"}
          %option{:selected => "selected"} Choose...
          %option{:value => "1"} 2
          %option{:value => "2"} 4
          %option{:value => "3"} 5
          %option{:value => "3"} 6
      .col-auto.my-1
        %label.mr-sm-2{:for => "inlineFormCustomSelect"} Horse power
        %select#inlineFormCustomSelect.custom-select.mr-sm-2{ name: "car_describtion[horse_power]"}
          %option{:selected => "selected"} Choose...
          %option{:value => "1"} 110
          %option{:value => "2"} 130
          %option{:value => "3"} 150
          %option{:value => "3"} 180
      .col-auto.my-1
        %label.mr-sm-2{:for => "inlineFormCustomSelect"} Color
        %select#inlineFormCustomSelect.custom-select.mr-sm-2{ name: "car_describtion[color]"}
          %option{:selected => "selected"} Choose...
          %option{:value => "1"} Red
          %option{:value => "2"} Blue
          %option{:value => "3"} Yellow
          %option{:value => "3"} Green
    .form-group
      %button.btn.btn-outline-primary.my-2-my-sm-0{ type: "submit" }
        Prepare Ride

app/views/car_transfers/show.html.haml
#map{ width: "100%", "data-lat" => @car_transfer.lat, "data-lng" => @car_transfer.lng, "data-radius" => @car_transfer.radius}
%p
  Can you bring the car to this position
%hr/
%a.btn.btn-outline-success.my-2-my-sm-0{href: "/car_dash_2"}
  Yes
%a.btn.btn-outline-danger.my-2-my-sm-0{href: "/car_dash_2"}
  No

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ charset: "utf-8" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no" }
    %title
      VolvoShare
    = csrf_meta_tags
    %link{ rel: "stylesheet", href: "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css", integrity: "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm", crossorigin: "anonymous" }
    %link{ rel: "stylesheet", href: "https://unpkg.com/leaflet@1.3.1/dist/leaflet.css", integrity: "sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==", crossorigin: "" }

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %script{ src: "https://unpkg.com/leaflet@1.3.1/dist/leaflet.js", integrity: "sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==", crossorigin: "" }
    %script{ src: "https://code.jquery.com/jquery-3.3.1.min.js", integrity: "sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=", crossorigin: "anonymous" }
    %script{ src: "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js", integrity: "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl", crossorigin: "anonymous" }
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      %a.navbar-brand{ href: "/" }
        VS
      %button.navbar-toggler#hide_forms{ type: "button", "data-toggle" => "collapse", "data-target" => "#navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation" }
        %span.navbar-toggler-icon
      - if current_user.present?
        .collapse.navbar-collapse#navbarSupportedContent
          %ul.navbar-nav.mr-auto
            %li.nav-item.dropdown
              %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Car
              .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
                %a.dropdown-item{:href => new_car_transfer_path} Book
                .dropdown-divider
                %a.dropdown-item{:href => "/karma/add?karma=70"} Clean
                %a.dropdown-item{:href => "/karma/add?karma=20"} Fill-Up
                %a.dropdown-item{:href => "/karma/add?karma=30"} Relocate
            %li.nav-item
              %a.nav-link{ href: products_path}
                Products
            %li.nav-item
              %a.nav-link{ href: profile_path(current_user)}
                Profile
            %li.nav-item
              %a.nav-link{ href: profiles_path}
                Best List
    .container
      = yield

app/views/layouts/car_dash.html.haml
!!!
%html
  %head
    %meta{ charset: "utf-8" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no" }
    %title
      VolvoShare
    = csrf_meta_tags
    %link{ rel: "stylesheet", href: "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css", integrity: "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm", crossorigin: "anonymous" }
    %link{ rel: "stylesheet", href: "https://unpkg.com/leaflet@1.3.1/dist/leaflet.css", integrity: "sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==", crossorigin: "" }

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %script{ src: "https://unpkg.com/leaflet@1.3.1/dist/leaflet.js", integrity: "sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==", crossorigin: "" }
    %script{ src: "https://code.jquery.com/jquery-3.3.1.min.js", integrity: "sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=", crossorigin: "anonymous" }
    %script{ src: "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js", integrity: "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl", crossorigin: "anonymous" }
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container-fluid
      = yield

app/views/pages/car_dash_1.html.haml
%img{:alt => "Computer Hope", :height => "25", :src => "/volvo_share_logo.png", :width => "70"}/
%br/
%br/
.col-auto.my-1
  %label.mr-sm-2{:for => "inlineFormCustomSelect"} Hey! Was it easy to find the car?
  %br/
  %hr/
  %a.btn.btn-outline-success.my-2-my-sm-0{href: "/car_dash_2"}
    Yes
  %a.btn.btn-outline-success.my-2-my-sm-0{href: "/car_dash_2"}
    No

app/views/pages/car_dash_2.html.haml
%img{:alt => "Computer Hope", :height => "25", :src => "/volvo_share_logo.png", :width => "70"}/
%br/
%br/
.col-auto.my-1
  %label.mr-sm-2{:for => "inlineFormCustomSelect"} Is the car clean?
  %hr/
  %a.btn.btn-outline-success.my-2-my-sm-0{href: "/car_dash_3"}
    Yes
  %a.btn.btn-outline-success.my-2-my-sm-0{href: "/car_dash_3"}
    No

app/views/pages/car_dash_3.html.haml
%img{:alt => "Computer Hope", :height => "25", :src => "volvo_share_logo.png", :width => "70"}/
%br/
%br/
.col-auto.my-1
  %label.mr-sm-2{:for => "inlineFormCustomSelect"} Are you happy with your ride?
  %hr/
  %a.btn.btn-outline-success.my-2-my-sm-0{href: "/car_dash_end"}
    Yes
  %a.btn.btn-outline-success.my-2-my-sm-0{href: "/car_dash_end"}
    No

app/views/pages/car_dash_end.html.haml
.jumbotron
  %h1
    Thanks, you got 50 Viking Horns for answering the questions. Have a nice ride!

app/views/pages/car_request.html.haml
%form.form.inline.my-2.my-lg-0{ action: "/request_taken", method: "get"}
  #prepare_ride
    .form-group
      %input.form-control.mr.sm-2{ placeholder: "My Location"}
    .form-group
      %input.form-control.mr.sm-2{ placeholder: "Destination"}
    .form-group
      %label{ for: "exampleFormControlSelect1" }
        Area where car should be placed:
      %select.form-control#exampleFormControlSelect1
        %option
          50m
        %option
          100m
        %option
          200m
        %option
          500m
    .form-group
      %button.btn#showMoreFiltersBtn
        Show more filters
    .form-row.align-items-center#additionalItems
      .col-auto.my-1
        %label.mr-sm-2{ for: "inlineFormCustomSelect" }
          Car Type
        %select.custom-select.mr-sm-2#inlineFormCustomSelect
          %option{ selected: true }
            Choose...
          %option
            Volvo 1
          %option
            Volvo 2
          %option
            Volvo 3
          %option
            Volvo 4
          %option
            Volvo 5
          %option
            Volvo 6
      .col-auto.my-1
        %label.mr-sm-2{:for => "inlineFormCustomSelect"} Number of seats
        %select#inlineFormCustomSelect.custom-select.mr-sm-2
          %option{:selected => "selected"} Choose...
          %option{:value => "1"} 2
          %option{:value => "2"} 4
          %option{:value => "3"} 5
          %option{:value => "3"} 6
      .col-auto.my-1
        %label.mr-sm-2{:for => "inlineFormCustomSelect"} Horse power
        %select#inlineFormCustomSelect.custom-select.mr-sm-2
          %option{:selected => "selected"} Choose...
          %option{:value => "1"} 110
          %option{:value => "2"} 130
          %option{:value => "3"} 150
          %option{:value => "3"} 180
      .col-auto.my-1
        %label.mr-sm-2{:for => "inlineFormCustomSelect"} Color
        %select#inlineFormCustomSelect.custom-select.mr-sm-2
          %option{:selected => "selected"} Choose...
          %option{:value => "1"} Red
          %option{:value => "2"} Blue
          %option{:value => "3"} Yellow
          %option{:value => "3"} Green
    .form-group
      %button.btn.btn-outline-primary.my-2-my-sm-0{ type: "submit" }
        Prepare Ride

app/views/pages/index.html.haml
#mapid{ width: '100%' }
-#%form
  -#.form-group
    -#%select.form-control#request_car_distance{ name: "radius"}
      -#%option{ value: "50"} 50m
      -#%option{ value: "100"} 100m
      -#%option{ value: "200" } 200m
      -#%option{ value: "500" } 500m

app/views/pages/request_taken.html.haml
.jumbotron
  %h1
    Your car will be there

app/views/products/index.html.haml
%table.table
  - @products.each do |product|
    %tr
      %td= product.title
      %td= product.description
      %td= product.price.to_s + " Viking Horns"
      %td= link_to "buy", product_buy_path(product)

app/views/profiles/index.html.haml
%table.table
  - @users.each do |user|
    %tr
      %td= link_to user.nickname, profile_path(user)
      %td= user.karma.to_s + " Viking Horns"

app/views/profiles/show.html.haml
.card
  %img{:alt => "volvo_viking", :src => "http://lorempixel.com/200/400"}/
  %h3= @user.nickname
  - if @user == current_user
    = form_for(:current_user, method: :put, action: profile_path(current_user)) do
      .col-sm-6
        .form-group.row
          %label{:for => "formGroupExampleInput"} Enter a nickname which will be visible to other users:
          %input#formGroupExampleInput.form-control{:placeholder => "Volvo Viking #Example", :type => "text", name: "nickname"}/
          %input.btn.btn-primary{value: "save", type: "submit"}
      .form-group.row
        %label.col-sm-4.col-form-label{:for => "staticEmail"} Email:
        .col-sm-8
          %input#staticEmail.form-control-plaintext{:readonly => "readonly", :type => "text", :value => @user.email}/
      .form-group.row
        %label.col-sm-4.col-form-label{:for => "staticEmail"} Payment Method:
        .col-sm-8
          %input#staticEmail.form-control-plaintext{:readonly => "readonly", :type => "text", :value => "Mastercard *********123"}/
      %ul.list-group
        %h6 Recently purchased items:
        - @user.products.each do |product|
          %li.list-group-item.list-group-item-success= product.title
  %hr/
  %h5
    Points:
    = @user.karma